on:
  workflow_call:
    inputs:
      go-version:
        required: false
        type: string
        default: '1.20'
      release-args:
        required: false
        type: string
        default: ''

jobs:
  go-releaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: ${{ inputs.go-version }}

      - uses: goreleaser/goreleaser-action@v4.2.0
        with:
          args: release --rm-dist ${{ inputs.release-args }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
